# Site settings
title:          Kleis
description:    "Kleis Technology SA"
url:            "https://www.kleis.ch"

# Google Analytics
google_analytics: UA-148727142-1

# Author
author:
  name:         Kleis Technology SA
  url:          https://www.kleis.ch
  email:        info@kleis.ch

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

collections:
  associates:

# Permalinks
permalink:      /:year-:month-:day/:title.html
paginate:       5
paginate_path:  /blog/page:num/

lang: fr

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
